package main

import (
	"database/sql"

	_ "github.com/lib/pq"
)

func insertGame(game *Game, db *sql.DB) error {
	// TODO: Prepare just once
	stmt, err := db.Prepare(query)

	if err != nil {
		panic(err)
	}

	uniqueGameID := getUniqueGameID(game)

	_, err = stmt.Exec(
		uniqueGameID,
		game.Date,
		game.NumberOfGame,
		game.DayOfWeek,
		game.VisitingTeam,
		game.VisitingTeamLeague,
		game.VisitingGameNumber,
		game.HomeTeam,
		game.HomeTeamLeague,
		game.HomeTeamGameNumber,
		game.VisitingTeamScore,
		game.HomeTeamScore,
		game.GameLengthInOuts,
		game.DayNightIndicator,
		game.CompletionInformation,
		game.ForfeitInformation,
		game.ProtestInformation,
		game.ParkID,
		game.Attendance,
		game.TimeOfGameInMins,
		game.VisitingLineScore,
		game.HomeLineScore,
		game.VisitingAB,
		game.VisitingH,
		game.Visiting2B,
		game.Visiting3B,
		game.VisitingHR,
		game.VisitingRBI,
		game.VisitingSH,
		game.VisitingSF,
		game.VisitingHBP,
		game.VisitingBB,
		game.VisitingIBB,
		game.VisitingK,
		game.VisitingSB,
		game.VisitingCS,
		game.VisitingGIDP,
		game.VisitingCI,
		game.VisitingLOB,
		game.VisitingPitchersUsed,
		game.VisitingIndividualEarnedRuns,
		game.VisitingTeamEarnedRuns,
		game.VisitingWildPitches,
		game.VisitingBalks,
		game.VisitingPutouts,
		game.VisitingAssists,
		game.VisitingErrors,
		game.VisitingPassedBalls,
		game.VisitingDoublePlays,
		game.VisitingTriplePlays,
		game.HomeAB,
		game.HomeH,
		game.Home2B,
		game.Home3B,
		game.HomeHR,
		game.HomeRBI,
		game.HomeSH,
		game.HomeSF,
		game.HomeHBP,
		game.HomeBB,
		game.HomeIBB,
		game.HomeK,
		game.HomeSB,
		game.HomeCS,
		game.HomeGIDP,
		game.HomeCI,
		game.HomeLOB,
		game.HomePitchersUsed,
		game.HomeIndividualEarnedRuns,
		game.HomeTeamEarnedRuns,
		game.HomeWildPitches,
		game.HomeBalks,
		game.HomePutouts,
		game.HomeAssists,
		game.HomeErrors,
		game.HomePassedBalls,
		game.HomeDoublePlays,
		game.HomeTriplePlays,
		game.HomePlateUmpireID,
		game.HomePlateUmpireName,
		game.FirstBaseUmpireID,
		game.FirstBaseUmpireName,
		game.SecondBaseUmpireID,
		game.SecondBaseUmpireName,
		game.ThirdBaseUmpireID,
		game.ThirdBaseUmpireName,
		game.LeftFieldUmpireID,
		game.LeftFieldUmpireName,
		game.RightFieldUmpireID,
		game.RightFieldUmpireName,
		game.VisitingManagerID,
		game.VisitingManagerName,
		game.HomeManagerID,
		game.HomeManagerName,
		game.WinningPitcherID,
		game.WinningPitcherName,
		game.LosingPitcherID,
		game.LosingPitcherName,
		game.SavingPitcherID,
		game.SavingPitcherName,
		game.GameWinningRBIBatterID,
		game.GameWinningRBIBatterName,
		game.VisitingStartingPitcherID,
		game.VisitingStartingPitcherName,
		game.HomeStartingPitcherID,
		game.HomeStartingPitcherName,
		game.VisitingPlayer1ID,
		game.VisitingPlayer1Name,
		game.VisitingPlayer1Position,
		game.VisitingPlayer2ID,
		game.VisitingPlayer2Name,
		game.VisitingPlayer2Position,
		game.VisitingPlayer3ID,
		game.VisitingPlayer3Name,
		game.VisitingPlayer3Position,
		game.VisitingPlayer4ID,
		game.VisitingPlayer4Name,
		game.VisitingPlayer4Position,
		game.VisitingPlayer5ID,
		game.VisitingPlayer5Name,
		game.VisitingPlayer5Position,
		game.VisitingPlayer6ID,
		game.VisitingPlayer6Name,
		game.VisitingPlayer6Position,
		game.VisitingPlayer7ID,
		game.VisitingPlayer7Name,
		game.VisitingPlayer7Position,
		game.VisitingPlayer8ID,
		game.VisitingPlayer8Name,
		game.VisitingPlayer8Position,
		game.VisitingPlayer9ID,
		game.VisitingPlayer9Name,
		game.VisitingPlayer9Position,
		game.HomePlayer1ID,
		game.HomePlayer1Name,
		game.HomePlayer1Position,
		game.HomePlayer2ID,
		game.HomePlayer2Name,
		game.HomePlayer2Position,
		game.HomePlayer3ID,
		game.HomePlayer3Name,
		game.HomePlayer3Position,
		game.HomePlayer4ID,
		game.HomePlayer4Name,
		game.HomePlayer4Position,
		game.HomePlayer5ID,
		game.HomePlayer5Name,
		game.HomePlayer5Position,
		game.HomePlayer6ID,
		game.HomePlayer6Name,
		game.HomePlayer6Position,
		game.HomePlayer7ID,
		game.HomePlayer7Name,
		game.HomePlayer7Position,
		game.HomePlayer8ID,
		game.HomePlayer8Name,
		game.HomePlayer8Position,
		game.HomePlayer9ID,
		game.HomePlayer9Name,
		game.HomePlayer9Position,
		game.AdditionalInformation,
		game.AcquisitionInformation,
	)

	return err
}

const query = `INSERT INTO game (
id,
game_date,
number_of_game,
day_of_week,
visiting_team,
visiting_team_league,
visiting_game_number,
home_team,
home_team_league,
home_team_game_number,
visiting_team_score,
home_team_score,
game_length_in_outs,
day_night_indicator,
completion_information,
forfeit_information,
protest_information,
park_id,
attendance,
time_of_game_in_mins,
visiting_line_score,
home_line_score,
visiting_ab   ,
visiting_h    ,
visiting_2B   ,
visiting_3B   ,
visiting_hr   ,
visiting_rbi  ,
visiting_sh   ,
visiting_sf   ,
visiting_hbp  ,
visiting_bb   ,
visiting_ibb  ,
visiting_k    ,
visiting_sb   ,
visiting_cs   ,
visiting_gidp ,
visiting_ci   ,
visiting_lob  ,
visiting_pitchers_used         ,
visiting_individual_earned_runs ,
visiting_team_earned_runs       ,
visiting_wild_pitches          ,
visiting_balks                 ,
visiting_putouts     ,
visiting_assists     ,
visiting_errors      ,
visiting_passed_balls ,
visiting_double_plays ,
visiting_triple_plays ,
home_ab   ,
home_h    ,
home_2B   ,
home_3B   ,
home_hr   ,
home_rbi  ,
home_sh   ,
home_sf   ,
home_hbp  ,
home_bb   ,
home_ibb  ,
home_k    ,
home_sb   ,
home_cs   ,
home_gidp ,
home_ci   ,
home_lob  ,
home_pitchers_used         ,
home_individual_earned_runs ,
home_team_earned_runs       ,
home_wild_pitches          ,
home_balks          ,
home_putouts     ,
home_assists     ,
home_errors      ,
home_passed_balls ,
home_double_plays ,
home_triple_plays ,
home_plate_umpire_id    ,
home_plate_umpire_name  ,
first_base_umpire_id    ,
first_base_umpire_name  ,
second_base_umpire_id   ,
second_base_umpire_name ,
third_base_umpire_id    ,
third_base_umpire_name  ,
left_field_umpire_id    ,
left_field_umpire_name  ,
right_field_umpire_id   ,
right_field_umpire_name ,
visiting_manager_id   ,
visiting_manager_name ,
home_manager_id       ,
home_manager_name     ,
winning_pitcher_id   ,
winning_pitcher_name ,
losing_pitcher_id    ,
losing_pitcher_name  ,
saving_pitcher_id    ,
saving_pitcher_name  ,
game_winning_rbi_batter_id   ,
game_winning_rbi_batter_name ,
visiting_starting_pitcher_id   ,
visiting_starting_pitcher_name ,
home_starting_pitcher_id       ,
home_starting_pitcher_name     ,
visiting_player1_id       ,
visiting_player1_name     ,
visiting_player1_position ,
visiting_player2_id       ,
visiting_player2_name     ,
visiting_player2_position ,
visiting_player3_id       ,
visiting_player3_name     ,
visiting_player3_position ,
visiting_player4_id       ,
visiting_player4_name     ,
visiting_player4_position ,
visiting_player5_id       ,
visiting_player5_name     ,
visiting_player5_position ,
visiting_player6_id       ,
visiting_player6_name     ,
visiting_player6_position ,
visiting_player7_id       ,
visiting_player7_name     ,
visiting_player7_position ,
visiting_player8_id       ,
visiting_player8_name     ,
visiting_player8_position ,
visiting_player9_id       ,
visiting_player9_name     ,
visiting_player9_position ,
home_player1_id       ,
home_player1_name     ,
home_player1_position ,
home_player2_id       ,
home_player2_name     ,
home_player2_position ,
home_player3_id       ,
home_player3_name     ,
home_player3_position ,
home_player4_id       ,
home_player4_name     ,
home_player4_position ,
home_player5_id       ,
home_player5_name     ,
home_player5_position ,
home_player6_id       ,
home_player6_name     ,
home_player6_position ,
home_player7_id       ,
home_player7_name     ,
home_player7_position ,
home_player8_id       ,
home_player8_name     ,
home_player8_position ,
home_player9_id       ,
home_player9_name     ,
home_player9_position ,
additional_information  ,
acquisition_information) VALUES (
$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59, $60, $61, $62, $63, $64, $65, $66, $67, $68, $69, $70, $71, $72, $73, $74, $75, $76, $77, $78, $79, $80, $81, $82, $83, $84, $85, $86, $87, $88, $89, $90, $91, $92, $93, $94, $95, $96, $97, $98, $99, $100, $101, $102, $103, $104, $105, $106, $107, $108, $109, $110, $111, $112, $113, $114, $115, $116, $117, $118, $119, $120, $121, $122, $123, $124, $125, $126, $127, $128, $129, $130, $131, $132, $133, $134, $135, $136, $137, $138, $139, $140, $141, $142, $143, $144, $145, $146, $147, $148, $149, $150, $151, $152, $153, $154, $155, $156, $157, $158, $159, $160, $161, $162
)`
